web: gunicorn app.main:app --worker-class=uvicorn.workers.UvicornWorker --bind=0.0.0.0:${PORT}
newrelic-admin generate-config 5d24facbfc9164a9a13f0c2ef628d3a7a04aNRAL newrelic.ini
release: scripts/heroku_release.sh
